name: PR Test

on:
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: if fail
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}
          script: |
            const { issue: { number: pull_number }, repo: { owner, repo } } = context;
            await github.pulls.createReview({
              owner,
              repo,
              pull_number,
              body:"테스트코드를 다시 확인해주세요. ",
              event: "REQUEST_CHANGES"
            });
            await github.pulls.update({
              owner,
              repo,
              pull_number,
              state: "closed"
            });
        if: failure()
